version: "3.9"

services:

  backend:
    container_name: backend
    build:

      context: ./backend
      dockerfile: Dockerfile

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db_backend:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

    ports:
      - '8080:8080'
    networks:
      - db
      - backend

    depends_on:
      - db_backend

  frontend:
    container_name: frontend
    build:

      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db_backend:
    image: postgres:15.2
    container_name: db_backend
    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      - local:/var/lib/postgresql/data

  pgadmin_backend:
    image: dpage/pgadmin4:2023-03-01-1
    container_name: pgadmin_backend
    ports:
      - "5050:80"
    environment:

      PGADMIN_DEFAULT_EMAIL: vladik@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass

    volumes:
      - pgadmin_backend:/var/lib/pgadmin

volumes:
  local:
  pgadmin_backend: