version: "3.9"

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile