version: "3.9"

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

    ports:
      - '8080:8080'

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db_postgres:
    container_name: db_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - db_postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db_postgres
    restart: unless-stopped

  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin

      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - db_postgres
      restart: unless-stopped

networks:
  db_postgres:
      driver: bridge

volumes:
  db_postgres:
  pgadmin:

